### ISSUE TITLE
install error regarding phat and cechmate

### ISSUE THREAD

**Issue by bsjeong** [andresantoro/RHOSTS#1]
Hi,
thank you for your nice tools
When I install RHOSTS (pip install requirements.txt) in conda environment (python==3.8.0, even higher version), I got error messages like followings. This error message also occurred in "pip install phat==1.5.0 cechmate==0.0.10"
Any comment will be appreciated^^
Bumseok

Collecting phat==1.5.0a0 (from cechmate>=0.0.10->-r requirements.txt (line 6))
  Downloading phat-1.5.0a.tar.gz (4.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.7/4.7 MB 4.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  WARNING: Requested phat==1.5.0a0 from https://files.pythonhosted.org/packages/43/82/c14de81dc2953a71a060f72f2bc34c41996307956b162751f2a47e2c78f7/phat-1.5.0a.tar.gz (from cechmate>=0.0.10->-r requirements.txt (line 6)), but installing version 1.5.0
Discarding https://files.pythonhosted.org/packages/43/82/c14de81dc2953a71a060f72f2bc34c41996307956b162751f2a47e2c78f7/phat-1.5.0a.tar.gz (from https://pypi.org/simple/phat/): Requested phat==1.5.0a0 from https://files.pythonhosted.org/packages/43/82/c14de81dc2953a71a060f72f2bc34c41996307956b162751f2a47e2c78f7/phat-1.5.0a.tar.gz (from cechmate>=0.0.10->-r requirements.txt (line 6)) has inconsistent version: expected '1.5.0a0', but metadata has '1.5.0'
INFO: pip is looking at multiple versions of cechmate to determine which version is compatible with other requirements. This could take a while.
Collecting cechmate>=0.0.10 (from -r requirements.txt (line 6))
  Downloading cechmate-0.0.10-py3-none-any.whl.metadata (3.5 kB)
ERROR: Cannot install -r requirements.txt (line 6) because these package versions have conflicting dependencies.

The conflict is caused by:
    cechmate 0.1.0 depends on phat==1.5.0a0
    cechmate 0.0.10 depends on phat

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts

**Comment by andresantoro** [comment]
Hi, 

thanks for bringing this up. I provided a possible workaround for this issue here (OS systems and Linux platforms): https://github.com/andresantoro/RHOSTS/tree/main/High_order_TS
I've also modified the repository's README to include the link to that page. 
Let me know if, following those instructions, you manage to solve the issue.

**Comment by bsjeong** [comment]
Thanks for quick response.
phat is successfully installed with "pip install --use-deprecated=legacy-resolver -r requirements.txt".
It produce, however, following error messages. Can I ignore it?

.....
Successfully built phat
Installing collected packages: hopcroftkarp, persim, phat, cechmate
ERROR: pip's legacy dependency resolver does not consider dependency conflicts when selecting packages. 
This behaviour is the source of the following dependency conflicts.
cechmate 0.1.0 requires phat==1.5.0a0, but you'll have phat 1.5.0 which is incompatible.

**Comment by andresantoro** [comment]
In that case, you should uninstall phat and reinstall manually the package, as suggested in the Readme, by downloading  phat 1.5.0a at the following link:

https://files.pythonhosted.org/packages/43/82/c14de81dc2953a71a060f72f2bc34c41996307956b162751f2a47e2c78f7/phat-1.5.0a.tar.gz#sha256=51e7fe5e05adf5c7e0895765572fff05b979731234251f13011610d71d4980ab

**Comment by andresantoro** [comment]
I trust that you've managed to address the conflicts after reviewing the latest comment. Marking it as resolved
